server {
    listen 80;
    server_name next-clean.demo.minimonster.id;
    server_tokens off;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name next-clean.demo.minimonster.id;
    server_tokens off;

    ssl_certificate /etc/letsencrypt/live/next-clean.demo.minimonster.id/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/next-clean.demo.minimonster.id/privkey.pem;

    ssl_buffer_size 8k;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers ECDH+AESGCM:ECDH+AES256:ECDH+AES128:DH+3DES:!ADH:!AECDH:!MD5;

    location / {
        proxy_pass http://nextclean-webserver:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
